from typing import Optional
from dataclasses import dataclass

class Event:
    """Base Event Class"""
    pass

@dataclass
class MarketEvent(Event):
    """
    Market Data Update Event.
    Triggered when new market data (candle/tick) is received.
    """
    time: int # Unix timestamp
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    
@dataclass
class SignalEvent(Event):
    """
    Signal generated by the Strategy.
    """
    time: int
    symbol: str
    signal_type: str # "LONG", "SHORT", "EXIT"
    strength: float = 1.0
    strategy_id: str = "UNKNOWN"

@dataclass
class OrderEvent(Event):
    """
    Order execution request.
    """
    time: int
    symbol: str
    order_type: str # "MARKET", "LIMIT"
    quantity: float
    direction: str # "BUY", "SELL"
    limit_price: Optional[float] = None

@dataclass
class FillEvent(Event):
    """
    Order Fill Confirmation.
    """
    time: int
    symbol: str
    exchange: str
    quantity: float
    direction: str
    fill_cost: Optional[float] = None
    commission: Optional[float] = None
